#!/usr/bin/env python
"""One-command campaign orchestrator run — Layer 4.6.

    python campaigns/run.py

Generates fresh synthetic order history (seeded, deterministic), computes
every segment with pure Python (no LLM), then for each segment: asks the
LLM to propose a campaign, runs every treatment-group member's offer
through the exact same deterministic policy engine, simulates redemption
against a held-out control group, and prints + saves a results table.

Nothing here is a real customer or a real sale — see docs/046-campaigns.md
for exactly what's synthetic, what's deterministic, and what's simulated.
"""

import argparse
import json
import os
import sys
from dataclasses import asdict
from datetime import datetime, timezone
from pathlib import Path

_BACKEND_DIR = Path(__file__).resolve().parents[1] / "backend"
sys.path.insert(0, str(_BACKEND_DIR))

# .env sets DATABASE_URL=sqlite:///./razorpay_agent.db — a path relative to
# the process's *working directory*, which is correct when the backend
# server is launched from backend/ but wrong here (this script is meant to
# be run from the repo root, per its own --help). Pin it to the real file
# explicitly, before app.core.config ever reads the environment, so this
# script always finds the same database the backend server uses rather
# than silently creating and seeding an empty one next to itself.
os.environ["DATABASE_URL"] = f"sqlite:///{(_BACKEND_DIR / 'razorpay_agent.db').as_posix()}"

# Same reasoning as demo.py / buyer_agent: Windows consoles default stdout
# to a codepage that can't encode ₹, and fully-buffer when not a real TTY.
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace", line_buffering=True)

from app.campaigns import segmentation  # noqa: E402
from app.campaigns.generator import generate_history  # noqa: E402
from app.campaigns.models import Customer, HistoricalOrder  # noqa: E402
from app.campaigns.service import CampaignError, run_campaign  # noqa: E402
from app.core.config import settings  # noqa: E402
from app.database import Base, SessionLocal, engine  # noqa: E402


def _banner(text: str) -> None:
    print("\n" + "=" * 72)
    print(text)
    print("=" * 72)


def _render_markdown(meta, segments, results: list, timestamp: str) -> str:
    lines = [
        f"# Campaign run — {timestamp}",
        "",
        f"Synthetic history: seed={meta.seed}, as_of={meta.as_of.isoformat()}",
        "",
        "## Segments (deterministic, no LLM)",
        "",
        "| Segment | Size | Description |",
        "|---|---|---|",
    ]
    for name, seg in segments.items():
        lines.append(f"| {name} | {seg.size} | {seg.description} |")

    lines += [
        "",
        "## Campaign results",
        "",
        "| Segment | Status | Discount | Offers sent | Blocked | Control | Redemptions | "
        "Treatment revenue | Control revenue | Incremental revenue | Discount cost | Net margin impact |",
        "|---|---|---|---|---|---|---|---|---|---|---|---|",
    ]
    for r in results:
        if r.status != "completed":
            lines.append(f"| {r.segment_name} | {r.status} | — | — | — | — | — | — | — | — | — | — |")
            continue
        m = r.measurement
        lines.append(
            f"| {r.segment_name} | completed | {r.proposal.discount_pct * 100:.0f}% | {m.offers_sent} | "
            f"{m.offers_blocked} | {m.control_size} | {m.redemptions} | "
            f"₹{m.treatment_revenue_paise / 100:.2f} | ₹{m.control_revenue_paise / 100:.2f} | "
            f"₹{m.incremental_revenue_paise / 100:.2f} | ₹{m.discount_cost_paise / 100:.2f} | "
            f"₹{m.net_margin_impact_paise / 100:.2f} |"
        )

    lines += ["", "## Blocked / failed segments (detail)", ""]
    any_blocked = False
    for r in results:
        if r.status != "completed":
            any_blocked = True
            lines.append(f"- **{r.segment_name}**: {r.reason}")
    if not any_blocked:
        lines.append("(none)")

    lines += ["", "## Proposals", ""]
    for r in results:
        if r.status != "completed":
            continue
        lines.append(f"- **{r.segment_name}**: {r.proposal.discount_pct * 100:.0f}% off {r.proposal.skus} — {r.proposal.message!r}")
        lines.append(f"  - rationale: {r.proposal.rationale!r}")

    lines += [
        "",
        "## What is simulated vs real",
        "",
        "- Customers and order history: **synthetic**, generated by app/campaigns/generator.py from a fixed seed — not real customers.",
        "- Segments: **real computation** (pure Python, deterministic) over that synthetic history.",
        "- Campaign proposal (SKUs, discount, message): a **real LLM call**, gated by the same policy engine as every other action in this project.",
        "- Policy decisions (ALLOW/DENY per customer): **real** — the exact same CampaignPolicyEngine a unit test exercises.",
        "- Redemption, conversion, and all revenue/margin figures above: **simulated** (seeded RNG against a documented probability model) "
        "— never observed behavior. See docs/046-campaigns.md.",
    ]
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate history, segment, propose, gate, and measure — one command.")
    parser.add_argument("--seed", type=int, default=42, help="Seed for synthetic history generation.")
    parser.add_argument("--campaign-seed", type=int, default=7, help="Seed for control-split + redemption simulation.")
    parser.add_argument("--output-dir", default=str(Path(__file__).parent / "results"))
    args = parser.parse_args()

    Base.metadata.create_all(bind=engine)
    db = SessionLocal()

    _banner("1. Generating synthetic order history")
    meta = generate_history(db, seed=args.seed, as_of=datetime.now(timezone.utc))
    n_customers = db.query(Customer).count()
    n_orders = db.query(HistoricalOrder).count()
    print(f"  seed={meta.seed}  as_of={meta.as_of.isoformat()}")
    print(f"  {n_customers} customers, {n_orders} orders")

    _banner("2. Computing segments (deterministic Python, no LLM)")
    segments = segmentation.compute_segments(
        db,
        meta.as_of,
        lapsed_days=settings.campaign_lapsed_days,
        repeat_min_orders=settings.campaign_repeat_min_orders,
        high_value_threshold_paise=settings.campaign_high_value_threshold_paise,
        category_loyal_min_share=settings.campaign_category_loyal_min_share,
    )
    for name, seg in segments.items():
        print(f"  {name:16s} {seg.size:3d} member(s) — {seg.description}")

    _banner("3-5. Proposing + gating + measuring one campaign per segment")
    results = []
    for name in segments:
        print(f"\n--- {name} ---")
        try:
            result = run_campaign(db, name, seed=args.campaign_seed)
        except CampaignError as e:
            print(f"  error: {e}")
            continue
        results.append(result)
        if result.status != "completed":
            print(f"  blocked: {result.reason}")
            continue
        m = result.measurement
        print(f"  proposal: {result.proposal.discount_pct * 100:.0f}% off {result.proposal.skus} — {result.proposal.message}")
        print(f"  offers sent={m.offers_sent}  blocked={m.offers_blocked}  control={m.control_size}  redemptions={m.redemptions}")
        print(
            f"  treatment revenue ₹{m.treatment_revenue_paise / 100:.2f}  control revenue ₹{m.control_revenue_paise / 100:.2f}  "
            f"(control conversion rate {m.control_conversion_rate * 100:.1f}%)"
        )
        print(f"  incremental revenue ₹{m.incremental_revenue_paise / 100:.2f}  discount cost ₹{m.discount_cost_paise / 100:.2f}")
        print(f"  NET MARGIN IMPACT ₹{m.net_margin_impact_paise / 100:.2f}" + ("  (negative — margin destroyed)" if m.net_margin_impact_paise < 0 else ""))

    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    stamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    timestamp_iso = datetime.now(timezone.utc).isoformat()

    payload = {
        "meta": {"seed": meta.seed, "as_of": meta.as_of.isoformat(), "n_customers": n_customers, "n_orders": n_orders, "timestamp": timestamp_iso},
        "segments": {name: {"size": seg.size, "description": seg.description} for name, seg in segments.items()},
        "results": [
            {
                "campaign_id": r.campaign_id,
                "segment_name": r.segment_name,
                "status": r.status,
                "reason": r.reason,
                "proposal": asdict(r.proposal) if r.proposal else None,
                "measurement": asdict(r.measurement) if r.measurement else None,
            }
            for r in results
        ],
    }
    json_path = output_dir / f"campaign_run_{stamp}.json"
    json_path.write_text(json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8")
    (output_dir / "latest.json").write_text(json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8")

    md = _render_markdown(meta, segments, results, timestamp_iso)
    md_path = output_dir / f"campaign_run_{stamp}.md"
    md_path.write_text(md, encoding="utf-8")
    (output_dir / "latest.md").write_text(md, encoding="utf-8")

    _banner("Done")
    print(f"Saved: {json_path}\n        {md_path}")

    db.close()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
