"""layer 4.8: demand signals, notifications, discounts, nullable role

Revision ID: 3c791daabe3e
Revises: ed91af887afb
Create Date: 2026-09-03 15:41:52.103984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c791daabe3e'
down_revision: Union[str, None] = 'ed91af887afb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demand_signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_query', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=True),
    sa.Column('extracted_attributes', sa.JSON(), nullable=True),
    sa.Column('matched_sku', sa.String(length=32), nullable=True),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_demand_signals_category'), 'demand_signals', ['category'], unique=False)
    op.create_index(op.f('ix_demand_signals_matched_sku'), 'demand_signals', ['matched_sku'], unique=False)
    op.create_index(op.f('ix_demand_signals_outcome'), 'demand_signals', ['outcome'], unique=False)
    op.create_index(op.f('ix_demand_signals_session_id'), 'demand_signals', ['session_id'], unique=False)
    op.create_table('merchant_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('dedupe_key', sa.String(length=120), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('suggested_action', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('acted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dismissed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_merchant_notifications_dedupe_key'), 'merchant_notifications', ['dedupe_key'], unique=True)
    op.create_index(op.f('ix_merchant_notifications_type'), 'merchant_notifications', ['type'], unique=False)
    op.add_column('products', sa.Column('discount_pct', sa.Float(), nullable=True))
    # SQLite has no ALTER COLUMN — batch mode rebuilds the table under the hood.
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
                   existing_type=sa.VARCHAR(length=20),
                   nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
                   existing_type=sa.VARCHAR(length=20),
                   nullable=False)
    op.drop_column('products', 'discount_pct')
    op.drop_index(op.f('ix_merchant_notifications_type'), table_name='merchant_notifications')
    op.drop_index(op.f('ix_merchant_notifications_dedupe_key'), table_name='merchant_notifications')
    op.drop_table('merchant_notifications')
    op.drop_index(op.f('ix_demand_signals_session_id'), table_name='demand_signals')
    op.drop_index(op.f('ix_demand_signals_outcome'), table_name='demand_signals')
    op.drop_index(op.f('ix_demand_signals_matched_sku'), table_name='demand_signals')
    op.drop_index(op.f('ix_demand_signals_category'), table_name='demand_signals')
    op.drop_table('demand_signals')
    # ### end Alembic commands ###
