"""product views and campaign offer sku

Revision ID: 9634c6403055
Revises: e171db592c31
Create Date: 2026-09-03 11:56:14.490810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9634c6403055'
down_revision: Union[str, None] = 'e171db592c31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('sku', sa.String(length=32), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('viewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_views_sku'), 'product_views', ['sku'], unique=False)
    op.create_index(op.f('ix_product_views_user_id'), 'product_views', ['user_id'], unique=False)
    op.create_index(op.f('ix_product_views_viewed_at'), 'product_views', ['viewed_at'], unique=False)
    op.add_column('campaign_offers', sa.Column('sku', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaign_offers', 'sku')
    op.drop_index(op.f('ix_product_views_viewed_at'), table_name='product_views')
    op.drop_index(op.f('ix_product_views_user_id'), table_name='product_views')
    op.drop_index(op.f('ix_product_views_sku'), table_name='product_views')
    op.drop_table('product_views')
    # ### end Alembic commands ###
