"""audit token usage and cost tracking

Revision ID: bf47ae324316
Revises: a837a0dce93f
Create Date: 2026-09-02 19:24:17.392302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf47ae324316'
down_revision: Union[str, None] = 'a837a0dce93f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_events', sa.Column('prompt_tokens', sa.Integer(), nullable=True))
    op.add_column('audit_events', sa.Column('completion_tokens', sa.Integer(), nullable=True))
    op.add_column('audit_events', sa.Column('total_tokens', sa.Integer(), nullable=True))
    op.add_column('audit_events', sa.Column('cost_paise', sa.Integer(), nullable=True))
    op.add_column('audit_events', sa.Column('fallback_used', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit_events', 'fallback_used')
    op.drop_column('audit_events', 'cost_paise')
    op.drop_column('audit_events', 'total_tokens')
    op.drop_column('audit_events', 'completion_tokens')
    op.drop_column('audit_events', 'prompt_tokens')
    # ### end Alembic commands ###
