"""product updated_at for catalog feed

Revision ID: cde476b1d5cb
Revises: 6976d1476f34
Create Date: 2026-09-02 23:17:46.138593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cde476b1d5cb'
down_revision: Union[str, None] = '6976d1476f34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite's ALTER TABLE ADD COLUMN refuses a non-constant default
    # (CURRENT_TIMESTAMP included) on an existing table — a fixed literal is
    # the only thing it accepts. Real inserts going forward get a real
    # timestamp from the model's Python-side default; this backfill value is
    # only ever seen by existing seed rows.
    op.add_column(
        'products',
        sa.Column(
            'updated_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text("'1970-01-01 00:00:00'")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'updated_at')
    # ### end Alembic commands ###
