"""product cost_paise for margin floor rule

Revision ID: dab1b45d626a
Revises: cde476b1d5cb
Create Date: 2026-09-03 11:15:50.123280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dab1b45d626a'
down_revision: Union[str, None] = 'cde476b1d5cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 0 is a placeholder backfill only — re-running scripts/seed.py (idempotent,
    # upsert-by-sku) immediately overwrites every row with its real cost_paise
    # from products.json.
    op.add_column('products', sa.Column('cost_paise', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'cost_paise')
    # ### end Alembic commands ###
