"""campaign tables

Revision ID: e171db592c31
Revises: dab1b45d626a
Create Date: 2026-09-03 11:17:24.654533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e171db592c31'
down_revision: Union[str, None] = 'dab1b45d626a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign_customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_key', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_customers_customer_key'), 'campaign_customers', ['customer_key'], unique=True)
    op.create_table('campaign_generation_meta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaign_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.String(length=64), nullable=False),
    sa.Column('segment_name', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('proposal', sa.JSON(), nullable=True),
    sa.Column('result_summary', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_runs_campaign_id'), 'campaign_runs', ['campaign_id'], unique=True)
    op.create_table('campaign_historical_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('placed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_paise', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['campaign_customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_historical_orders_customer_id'), 'campaign_historical_orders', ['customer_id'], unique=False)
    op.create_index(op.f('ix_campaign_historical_orders_placed_at'), 'campaign_historical_orders', ['placed_at'], unique=False)
    op.create_table('campaign_offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.String(length=64), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('group', sa.String(length=20), nullable=False),
    sa.Column('decision', sa.String(length=30), nullable=True),
    sa.Column('rule_name', sa.String(length=60), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('discount_pct', sa.Float(), nullable=True),
    sa.Column('redeemed', sa.Boolean(), nullable=False),
    sa.Column('revenue_paise', sa.Integer(), nullable=False),
    sa.Column('cogs_paise', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign_runs.campaign_id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['campaign_customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_offers_campaign_id'), 'campaign_offers', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_campaign_offers_customer_id'), 'campaign_offers', ['customer_id'], unique=False)
    op.create_table('campaign_historical_order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=32), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price_paise', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['campaign_historical_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_historical_order_items_order_id'), 'campaign_historical_order_items', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_campaign_historical_order_items_order_id'), table_name='campaign_historical_order_items')
    op.drop_table('campaign_historical_order_items')
    op.drop_index(op.f('ix_campaign_offers_customer_id'), table_name='campaign_offers')
    op.drop_index(op.f('ix_campaign_offers_campaign_id'), table_name='campaign_offers')
    op.drop_table('campaign_offers')
    op.drop_index(op.f('ix_campaign_historical_orders_placed_at'), table_name='campaign_historical_orders')
    op.drop_index(op.f('ix_campaign_historical_orders_customer_id'), table_name='campaign_historical_orders')
    op.drop_table('campaign_historical_orders')
    op.drop_index(op.f('ix_campaign_runs_campaign_id'), table_name='campaign_runs')
    op.drop_table('campaign_runs')
    op.drop_table('campaign_generation_meta')
    op.drop_index(op.f('ix_campaign_customers_customer_key'), table_name='campaign_customers')
    op.drop_table('campaign_customers')
    # ### end Alembic commands ###
