"""users and agent credentials

Revision ID: ed91af887afb
Revises: 9634c6403055
Create Date: 2026-09-03 12:46:42.018821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed91af887afb'
down_revision: Union[str, None] = '9634c6403055'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('google_sub', sa.String(length=120), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_google_sub'), 'users', ['google_sub'], unique=True)
    op.create_table('agent_credentials',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('owner_user_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('key_hash', sa.String(length=128), nullable=False),
    sa.Column('delivery_mode', sa.String(length=20), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('spend_limit_paise', sa.Integer(), nullable=False),
    sa.Column('spent_paise', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('standing_instruction', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_credentials_key_hash'), 'agent_credentials', ['key_hash'], unique=False)
    op.create_index(op.f('ix_agent_credentials_owner_user_id'), 'agent_credentials', ['owner_user_id'], unique=False)
    op.add_column('audit_events', sa.Column('principal_type', sa.String(length=20), nullable=True))
    op.add_column('audit_events', sa.Column('principal_id', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit_events', 'principal_id')
    op.drop_column('audit_events', 'principal_type')
    op.drop_index(op.f('ix_agent_credentials_owner_user_id'), table_name='agent_credentials')
    op.drop_index(op.f('ix_agent_credentials_key_hash'), table_name='agent_credentials')
    op.drop_table('agent_credentials')
    op.drop_index(op.f('ix_users_google_sub'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
