"""Campaign feature tables — all new, none touching the live cart/order
schema. Historical orders are synthetic (generated by
app/campaigns/generator.py), never real Razorpay transactions, so they get
their own tables rather than being forced through the payments Order model
(which is tied to idempotency keys, a Razorpay order id, and a state
machine that assumes a real checkout happened).
"""

from datetime import datetime, timezone

from sqlalchemy import Boolean, DateTime, Float, ForeignKey, Integer, JSON, String, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database import Base


def _utcnow() -> datetime:
    return datetime.now(timezone.utc)


class GenerationMeta(Base):
    """Single-row table: the seed and reference 'as of' date the synthetic
    history was generated against. Segmentation and campaign simulation
    read this instead of real wall-clock time — otherwise 'lapsed: no order
    in N days' would silently change answers depending on when the report
    happens to be re-run, which defeats 'deterministic, reproducible'."""

    __tablename__ = "campaign_generation_meta"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    seed: Mapped[int] = mapped_column(Integer, nullable=False)
    as_of: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    generated_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False, default=_utcnow)


class Customer(Base):
    __tablename__ = "campaign_customers"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    customer_key: Mapped[str] = mapped_column(String(32), unique=True, index=True, nullable=False)
    name: Mapped[str] = mapped_column(String(120), nullable=False)
    email: Mapped[str] = mapped_column(String(160), nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False, default=_utcnow)

    orders: Mapped[list["HistoricalOrder"]] = relationship(back_populates="customer")


class HistoricalOrder(Base):
    __tablename__ = "campaign_historical_orders"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    customer_id: Mapped[int] = mapped_column(ForeignKey("campaign_customers.id"), nullable=False, index=True)
    placed_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False, index=True)
    total_paise: Mapped[int] = mapped_column(Integer, nullable=False)

    customer: Mapped["Customer"] = relationship(back_populates="orders")
    items: Mapped[list["HistoricalOrderItem"]] = relationship(back_populates="order", cascade="all, delete-orphan")


class HistoricalOrderItem(Base):
    __tablename__ = "campaign_historical_order_items"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    order_id: Mapped[int] = mapped_column(ForeignKey("campaign_historical_orders.id"), nullable=False, index=True)
    # References the real product catalog by sku (not a strict FK — this
    # data is a standalone synthetic history, and shouldn't gain a hard
    # dependency on the live products table's row lifecycle). category is a
    # snapshot at order time, exactly like unit_price_paise, so segmentation
    # never needs to join back to the live catalog to work.
    sku: Mapped[str] = mapped_column(String(32), nullable=False)
    category: Mapped[str] = mapped_column(String(60), nullable=False)
    quantity: Mapped[int] = mapped_column(Integer, nullable=False)
    unit_price_paise: Mapped[int] = mapped_column(Integer, nullable=False)

    order: Mapped["HistoricalOrder"] = relationship(back_populates="items")


class CampaignRun(Base):
    __tablename__ = "campaign_runs"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    campaign_id: Mapped[str] = mapped_column(String(64), unique=True, index=True, nullable=False)
    segment_name: Mapped[str] = mapped_column(String(60), nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False, default=_utcnow)
    # "completed" | "blocked_at_segment" (SegmentSizeRule refused the whole
    # campaign before any customer was ever considered)
    status: Mapped[str] = mapped_column(String(20), nullable=False, default="completed")
    proposal: Mapped[dict | None] = mapped_column(JSON, nullable=True)
    result_summary: Mapped[dict | None] = mapped_column(JSON, nullable=True)


class CampaignOffer(Base):
    """One row per customer considered for a campaign — treatment or
    control. A control-group row's decision/rule/reason stay NULL forever:
    it is never evaluated by the policy engine and never targeted, which is
    what makes 'genuinely held out' a checkable fact, not a claim."""

    __tablename__ = "campaign_offers"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    campaign_id: Mapped[str] = mapped_column(String(64), ForeignKey("campaign_runs.campaign_id"), nullable=False, index=True)
    customer_id: Mapped[int] = mapped_column(ForeignKey("campaign_customers.id"), nullable=False, index=True)
    group: Mapped[str] = mapped_column(String(20), nullable=False)  # "treatment" | "control"
    decision: Mapped[str | None] = mapped_column(String(30), nullable=True)  # "ALLOW" | "DENY" | None
    rule_name: Mapped[str | None] = mapped_column(String(60), nullable=True)
    reason: Mapped[str | None] = mapped_column(Text, nullable=True)
    discount_pct: Mapped[float | None] = mapped_column(Float, nullable=True)
    # Simulated, never observed — see app/campaigns/simulation.py and
    # docs/046-campaigns.md for the documented redemption-probability model.
    redeemed: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    revenue_paise: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    cogs_paise: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
